#!/usr/bin/env bash
# Recompile only the named generated chunks and relink the composite.
#
# Why this exists. A full DOL-only rebuild is 206 objects and takes 90-150
# minutes, which is what makes each emitter change so expensive. Instruction
# counts are deterministic to about 0.02% (scripts/bench_instructions.sh), so a
# change measured on only the hot chunks is still resolvable even though its
# effect is diluted by the chunks that were not rebuilt. The top ten chunks are
# about 26% of the live play window, so an effect worth 5% inside them is about
# 1.3% overall - thirty times the resolution of the metric.
#
# The screening loop is therefore:
#
#   edit the emitter -> build dolrecomp -> regenerate all chunks (seconds)
#     -> scripts/recomp_chunks.sh          (~10-15 minutes)
#     -> scripts/bench_instructions.sh     (~3 minutes)
#
# and only a candidate the metric likes earns the full 206-object rebuild. The
# route digest still gates correctness: a screening run whose digest is not
# UNCHANGED is invalid and the candidate is discarded.
#
# Usage: scripts/recomp_chunks.sh [chunk_name ...]
#        scripts/recomp_chunks.sh --list

set -euo pipefail

cd "$(dirname "$0")/.."
root=$PWD
build=$root/build/composite-cycle-hybrid-o2-v2

# The hottest generated chunks in the live play window, from the rendered
# sample recorded in docs/status/CURRENT.md (share of the sampled main thread):
#   0201 15.7%  0144 3.6%  0015 1.5%  0145 1.2%  0181 1.1%
#   0200  1.0%  0187 0.6%  0203 0.5%  0188 0.4%  0148 0.4%
DEFAULT_CHUNKS="chunk_0201_text1_803256E0.c chunk_0144_text1_802416E0.c chunk_0015_text1_8003D6E0.c chunk_0145_text1_802456E0.c chunk_0181_text1_802D56E0.c chunk_0200_text1_803216E0.c chunk_0187_text1_802ED6E0.c chunk_0203_text1_8032D6E0.c chunk_0188_text1_802F16E0.c chunk_0148_text1_802516E0.c"

if [ "${1:-}" = "--list" ]; then
    for c in $DEFAULT_CHUNKS; do echo "$c"; done
    exit 0
fi

chunks=("$@")
if [ ${#chunks[@]} -eq 0 ]; then
    read -r -a chunks <<< "$DEFAULT_CHUNKS"
fi

echo "recomp_chunks: ${#chunks[@]} chunk(s)"
python3 - "$build" "${chunks[@]}" <<'PY'
import json, os, subprocess, sys, time
build = sys.argv[1]
want = set(sys.argv[2:])
db = json.load(open(os.path.join(build, "compile_commands.json")))
cmds = {}
for e in db:
    base = os.path.basename(e["file"])
    if base in want:
        cmds[base] = e.get("command") or " ".join(e.get("arguments", []))
missing = sorted(want - set(cmds))
if missing:
    sys.exit("recomp_chunks: not generated by this build: " + ", ".join(missing))
t = time.time()
for base, cmd in cmds.items():
    r = subprocess.run(["sh", "-c", cmd], cwd=build, capture_output=True)
    if r.returncode:
        sys.stderr.write(r.stderr.decode("utf8", "replace")[-600:])
        sys.exit("recomp_chunks: " + base + " failed")
    print("  rebuilt %s (%.1f min elapsed)" % (base, (time.time() - t) / 60), flush=True)
print("recompiled %d chunk(s) in %.1f min" % (len(cmds), (time.time() - t) / 60))
PY

# Relink by invoking the recorded link command directly rather than through
# CMake. `cmake --build` re-checks every object against its headers and sources,
# so a hand-compiled subset does not screen anything: if the change is to a
# header the emitted code includes - core/cpu.h, say - make rebuilds all 748
# objects and the twenty-minute loop becomes a two-hour one. That is exactly what
# happened on the first attempt. The link line is the same one CMake would run.
echo "recomp_chunks: relinking through the recorded link command"
link=$(cat "$build/CMakeFiles/gGZLE01_recomp.dir/link.txt")
( cd "$build" && eval "$link" ) || { echo "recomp_chunks: relink failed" >&2; exit 1; }
echo "recomp_chunks: composite is $(shasum -a 256 "$build/gGZLE01_recomp.dylib" | cut -c1-16)"
echo "recomp_chunks: now measure with scripts/bench_instructions.sh (digest must stay UNCHANGED)"
